//! A minimal single-connection TCP server that lives inside the WireGuard
//! tunnel, serving HTTP on port 80.
//!
//! It is NOT a general TCP stack — one connection at a time, no SACK, no window
//! scaling, no negotiated MSS — but it now **streams** responses so peak RAM is
//! O(1) regardless of body size, with a lite **go-back-N retransmit** + ACK-driven
//! send window and **HTTP Range** support, so even a multi-MB body serves reliably
//! over a lossy relayed (DERP) path. The body is never materialised: it is read on
//! demand from a re-readable [`BodySource`] (a `&'static` flash page, a small owned
//! `Vec`, or — forward-looking — a flash partition by offset), so a retransmit just
//! re-reads the same offsets.
//!
//! Two entry points:
//! * [`TcpServer::handle_stream`] + [`TcpServer::tick`] — the streaming path: emits
//!   each segment through a `send` callback (the caller encrypts + relays it), and
//!   `tick` drives RTO retransmits. This is what the DERP loop uses.
//! * [`TcpServer::handle`] — a back-compat batch shim returning `Vec<Vec<u8>>` that
//!   blasts the whole response at once (the old "a dropped segment = reload"
//!   semantics), kept so the direct UDP path compiles unchanged.

use alloc::boxed::Box;
use alloc::format;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

/// A control action requested by the in-tunnel web panel. The firmware reads it
/// via [`TcpServer::take_action`] after each request and forwards it to the
/// display/LED UI thread.
#[derive(Clone, Debug)]
pub enum TcpAction {
    LedOn,
    LedOff,
    ScreenOn,
    ScreenOff,
    Flash,
    Default,
    Text(String),
}

/// A re-readable body source addressed by absolute byte offset. Re-readability is
/// what makes go-back-N retransmit free of stored copies: any segment can be
/// regenerated by reading the same offset again.
pub trait FlashReader: Send {
    /// Fill `buf` from byte offset `off`; returns bytes written (`<= buf.len()`).
    fn read_at(&self, off: usize, buf: &mut [u8]) -> usize;
    fn len(&self) -> usize;
}

/// Where a response body's bytes come from. None is ever held whole in RAM beyond
/// the small `Owned` case (a few kB of dynamic output).
pub enum BodySource {
    /// A `&'static` flash slice (the agent HTML) — zero heap.
    Static(&'static [u8]),
    /// A small owned buffer (dynamic `/run`, `/mcp` output, a few kB).
    Owned(Vec<u8>),
    /// A large body read from flash by offset (e.g. a model file). Forward-looking:
    /// the abstraction ships now; wiring an actual partition route is separate.
    Flash { reader: Box<dyn FlashReader>, len: usize },
}

impl BodySource {
    fn total_len(&self) -> usize {
        match self {
            BodySource::Static(s) => s.len(),
            BodySource::Owned(v) => v.len(),
            BodySource::Flash { len, .. } => *len,
        }
    }

    /// Read body bytes at `off` into `buf`; returns bytes written (clamped to end).
    fn read_at(&self, off: usize, buf: &mut [u8]) -> usize {
        match self {
            BodySource::Static(s) => copy_clamped(s, off, buf),
            BodySource::Owned(v) => copy_clamped(v, off, buf),
            BodySource::Flash { reader, len } => {
                if off >= *len {
                    return 0;
                }
                let n = (*len - off).min(buf.len());
                reader.read_at(off, &mut buf[..n])
            }
        }
    }
}

fn copy_clamped(src: &[u8], off: usize, buf: &mut [u8]) -> usize {
    if off >= src.len() {
        return 0;
    }
    let n = (src.len() - off).min(buf.len());
    buf[..n].copy_from_slice(&src[off..off + n]);
    n
}

/// A routed HTTP response: status + content type + a (re-readable) body source.
pub struct HttpReply {
    pub status: u16,
    pub content_type: &'static str,
    pub source: BodySource,
}

impl HttpReply {
    /// 200 response served zero-copy from a `&'static` flash slice.
    pub fn ok_static(content_type: &'static str, body: &'static [u8]) -> Self {
        HttpReply { status: 200, content_type, source: BodySource::Static(body) }
    }

    /// 200 response from a small owned buffer (dynamic output).
    pub fn ok_owned(content_type: &'static str, body: Vec<u8>) -> Self {
        HttpReply { status: 200, content_type, source: BodySource::Owned(body) }
    }

    /// Materialise the whole body into a `Vec` — for callers that have a real TCP
    /// stream and just write it (e.g. the std `local_server`), so they don't need
    /// the streaming segmenter. Large `Flash` bodies are read in chunks.
    pub fn into_body(self) -> Vec<u8> {
        match self.source {
            BodySource::Static(s) => s.to_vec(),
            BodySource::Owned(v) => v,
            BodySource::Flash { reader, len } => {
                let mut out = vec![0u8; len];
                let mut off = 0;
                while off < len {
                    let n = reader.read_at(off, &mut out[off..]);
                    if n == 0 {
                        out.truncate(off);
                        break;
                    }
                    off += n;
                }
                out
            }
        }
    }
}

/// An application route handler. The firmware (the ESP-specific layer) installs
/// one via [`TcpServer::with_handler`] to serve its own paths (e.g. a PySpell
/// web page + `/run` API). It receives the HTTP method, path, query string and
/// request body (for `POST`). Returning `None` falls back to the built-in
/// control panel. Keeping this a plain `fn` pointer is what lets tailscale-core
/// stay free of any application/PySpell/ESP code — it only stores and calls it.
///
/// Note: the server reads only the first TCP segment, so the whole request
/// (headers + body) must fit in it — true for both small `GET` URLs and small
/// `POST` bodies.
pub type RouteFn = fn(method: &str, path: &str, query: &str, body: &[u8]) -> Option<HttpReply>;

const PROTO_TCP: u8 = 6;
const HTTP_PORT: u16 = 80;

const FIN: u8 = 0x01;
const SYN: u8 = 0x02;
const RST: u8 = 0x04;
const PSH: u8 = 0x08;
const ACK: u8 = 0x10;

/// Conservative inner TCP payload (tunnel MTU-safe under WireGuard + DERP).
const MSS: usize = 512;
/// Flat congestion window: how many bytes may be outstanding (unacked) at once.
const CWND: usize = 4 * MSS;
/// Base retransmit timeout (ms). Generous: a DERP-relayed RTT plus tick latency.
const RTO_BASE_MS: u32 = 1000;
/// Retransmit-timeout ceiling after exponential backoff.
const RTO_MAX_MS: u32 = 8000;
/// Give up on a connection that has made no progress for this long.
const MAX_CONN_MS: u64 = 30_000;
/// Give up after this many consecutive RTOs with no ACK progress.
const MAX_RTO_ATTEMPTS: u8 = 8;

/// The response currently being streamed. The body itself is never materialised;
/// it is read on demand from `source`. The wire response is `[headers][body]`,
/// addressed by one absolute offset space `[0, total_len)`.
struct RespState {
    headers: Vec<u8>,   // rendered status line + headers, kept for the conn
    hdr_len: usize,     // headers.len()
    source: BodySource, // re-readable body
    body_base: usize,   // first body offset to serve (Range start; 0 for full)
    total_len: usize,   // hdr_len + body bytes to serve (bytes to send before FIN)
    fin_sent: bool,     // FIN has been emitted at total_len
}

/// State for the (single) connection we're currently serving.
#[derive(Default)]
struct Conn {
    active: bool,
    client_ip: [u8; 4],
    our_ip: [u8; 4],
    client_port: u16,
    rcv_nxt: u32, // next sequence number we expect from the client

    iss: u32,      // our initial send sequence (the SYN's seq)
    snd_una: u32,  // oldest unacked seq (advances on ACK)
    snd_nxt: u32,  // next sequence number we will send
    peer_win: u32, // client's last advertised receive window (bytes)

    rto_ms: u32,        // current retransmit timeout
    rto_attempts: u8,   // consecutive RTOs with no ACK progress
    last_send_ms: u64,  // when we last (re)transmitted data
    opened_ms: u64,     // for the lifetime watchdog

    resp: Option<RespState>,
}

#[derive(Default)]
pub struct TcpServer {
    conn: Conn,
    action: Option<TcpAction>,
    /// Optional application route handler (see [`RouteFn`]).
    handler: Option<RouteFn>,
}

impl TcpServer {
    pub fn new() -> Self {
        Self::default()
    }

    /// Like [`new`](Self::new) but with an application route handler installed.
    pub fn with_handler(handler: RouteFn) -> Self {
        TcpServer { handler: Some(handler), ..Default::default() }
    }

    /// Take the control action (if any) requested by the most recent request.
    pub fn take_action(&mut self) -> Option<TcpAction> {
        self.action.take()
    }

    /// Streaming entry point: feed one inner IPv4 packet; emit reply segments one at
    /// a time via `send` (each a full inner IPv4+TCP packet for the caller to
    /// WireGuard-encrypt + relay). Peak RAM is one segment, regardless of body size.
    pub fn handle_stream(&mut self, inner: &[u8], now_ms: u64, mut send: impl FnMut(&[u8])) {
        self.process(inner, now_ms, false, &mut send);
    }

    /// Idle tick: drive RTO retransmits and the lifetime watchdog. The DERP/data
    /// loop calls this on every idle iteration (no frame to process).
    pub fn tick(&mut self, now_ms: u64, mut send: impl FnMut(&[u8])) {
        if !self.conn.active {
            return;
        }
        // Lifetime watchdog: a stuck transfer must not wedge the shared thread.
        if now_ms.saturating_sub(self.conn.opened_ms) > MAX_CONN_MS {
            self.reset_with_rst(&mut send);
            return;
        }
        let outstanding = self.conn.resp.is_some() && self.conn.snd_una != self.conn.snd_nxt;
        if !outstanding {
            return;
        }
        if now_ms.saturating_sub(self.conn.last_send_ms) < self.conn.rto_ms as u64 {
            return;
        }
        // RTO fired with no ACK progress.
        self.conn.rto_attempts = self.conn.rto_attempts.saturating_add(1);
        if self.conn.rto_attempts > MAX_RTO_ATTEMPTS {
            self.reset_with_rst(&mut send);
            return;
        }
        self.conn.rto_ms = self.conn.rto_ms.saturating_mul(2).min(RTO_MAX_MS);
        // Go-back-N: rewind snd_nxt to snd_una and re-send from there (regenerated
        // from the re-readable body source — no stored copies).
        self.conn.snd_nxt = self.conn.snd_una;
        if let Some(r) = self.conn.resp.as_mut() {
            r.fin_sent = false;
        }
        // Always allow at least one segment so a zero-window peer gets a probe.
        let win = self.send_window().max(1);
        self.pump(now_ms, win, &mut send);
    }

    /// Back-compat batch shim: blast the whole response at once (no retransmit) and
    /// return the segments. Kept so the direct UDP path (`dataplane.rs`, no
    /// lwip-bridge) compiles and behaves as before.
    pub fn handle(&mut self, inner: &[u8]) -> Vec<Vec<u8>> {
        let mut out = Vec::new();
        self.process(inner, 0, true, &mut |seg| out.push(seg.to_vec()));
        out
    }

    /// Shared packet processing. `blast = true` ignores the send window (batch shim);
    /// `blast = false` respects the ACK-driven window (streaming path).
    fn process(&mut self, inner: &[u8], now_ms: u64, blast: bool, send: &mut dyn FnMut(&[u8])) {
        if inner.len() < 20 || (inner[0] >> 4) != 4 || inner[9] != PROTO_TCP {
            return;
        }
        let ihl = (inner[0] & 0x0f) as usize * 4;
        let total = u16::from_be_bytes([inner[2], inner[3]]) as usize;
        if ihl < 20 || total < ihl + 20 || total > inner.len() {
            return;
        }
        let mut dst_ip = [0u8; 4];
        let mut src_ip = [0u8; 4];
        src_ip.copy_from_slice(&inner[12..16]);
        dst_ip.copy_from_slice(&inner[16..20]);

        let tcp = &inner[ihl..total];
        let sport = u16::from_be_bytes([tcp[0], tcp[1]]);
        let dport = u16::from_be_bytes([tcp[2], tcp[3]]);
        let seq = u32::from_be_bytes([tcp[4], tcp[5], tcp[6], tcp[7]]);
        let ack = u32::from_be_bytes([tcp[8], tcp[9], tcp[10], tcp[11]]);
        let data_off = (tcp[12] >> 4) as usize * 4;
        let flags = tcp[13];
        let win = u16::from_be_bytes([tcp[14], tcp[15]]) as u32;
        if data_off < 20 || data_off > tcp.len() {
            return;
        }
        let payload = &tcp[data_off..];

        if dport != HTTP_PORT {
            return; // only serve :80
        }

        // New connection: SYN.
        if flags & SYN != 0 {
            let iss = rand_u32();
            self.conn = Conn {
                active: true,
                client_ip: src_ip,
                our_ip: dst_ip,
                client_port: sport,
                rcv_nxt: seq.wrapping_add(1), // SYN consumes one sequence number
                iss,
                snd_una: iss,
                snd_nxt: iss,
                peer_win: win,
                rto_ms: RTO_BASE_MS,
                opened_ms: now_ms,
                ..Default::default()
            };
            send(&self.segment(SYN | ACK, &[]));
            self.conn.snd_nxt = self.conn.snd_nxt.wrapping_add(1); // our SYN consumes one
            return;
        }

        // Anything else must match the active connection.
        if !self.conn.active || src_ip != self.conn.client_ip || sport != self.conn.client_port {
            return;
        }

        if flags & RST != 0 {
            self.conn = Conn::default();
            return;
        }

        // Process the ACK field: advance snd_una, update the peer window.
        if flags & ACK != 0 {
            self.conn.peer_win = win;
            if seq_lt(self.conn.snd_una, ack) && !seq_lt(self.conn.snd_nxt, ack) {
                self.conn.snd_una = ack; // new, in-range ACK
                self.conn.rto_ms = RTO_BASE_MS;
                self.conn.rto_attempts = 0;
                // Fully acked (incl. FIN): free the body, keep the conn for the FIN.
                if let Some(r) = self.conn.resp.as_ref() {
                    if r.fin_sent && self.conn.snd_una == self.conn.snd_nxt {
                        self.conn.resp = None;
                    }
                }
            }
        }

        // Data carrying the HTTP request: route it (once) and start streaming.
        if !payload.is_empty() {
            self.conn.rcv_nxt = seq.wrapping_add(payload.len() as u32);
            if self.conn.resp.is_none() {
                self.build_response(payload);
            }
            let w = if blast { usize::MAX } else { self.send_window() };
            self.pump(now_ms, w, send);
            return;
        }

        // Pure FIN from the client: ack it and close.
        if flags & FIN != 0 {
            self.conn.rcv_nxt = seq.wrapping_add(1);
            send(&self.segment(ACK, &[]));
            self.conn = Conn::default();
            return;
        }

        // Bare ACK: a window may have opened — send more.
        let w = if blast { usize::MAX } else { self.send_window() };
        self.pump(now_ms, w, send);
    }

    /// Bytes we may have outstanding beyond `snd_una`, bounded by peer window + cwnd.
    fn send_window(&self) -> usize {
        (self.conn.peer_win as usize).min(CWND)
    }

    /// Response bytes already acknowledged (clamped to `[0, total_len]`).
    fn acked_bytes(&self) -> usize {
        let total = self.conn.resp.as_ref().map(|r| r.total_len).unwrap_or(0);
        let raw = self.conn.snd_una.wrapping_sub(self.conn.iss).wrapping_sub(1);
        ((raw as i32) as i64).clamp(0, total as i64) as usize
    }

    /// Response bytes already sent (clamped to `[0, total_len]`; excludes FIN).
    fn sent_bytes(&self) -> usize {
        let total = self.conn.resp.as_ref().map(|r| r.total_len).unwrap_or(0);
        let raw = self.conn.snd_nxt.wrapping_sub(self.conn.iss).wrapping_sub(1);
        ((raw as i32) as i64).clamp(0, total as i64) as usize
    }

    /// Splice `[headers][body]` at absolute offset `abs` into `buf`; returns bytes
    /// written. Headers occupy `[0, hdr_len)`; the body follows, read from `source`.
    fn read_response(&self, abs: usize, buf: &mut [u8]) -> usize {
        let r = match self.conn.resp.as_ref() {
            Some(r) => r,
            None => return 0,
        };
        let mut written = 0;
        let mut pos = abs;
        if pos < r.hdr_len {
            let n = (r.hdr_len - pos).min(buf.len());
            buf[..n].copy_from_slice(&r.headers[pos..pos + n]);
            written += n;
            pos += n;
            if written == buf.len() {
                return written;
            }
        }
        if pos >= r.hdr_len && pos < r.total_len {
            let body_off = r.body_base + (pos - r.hdr_len);
            written += r.source.read_at(body_off, &mut buf[written..]);
        }
        written
    }

    /// Emit not-yet-sent segments up to `window` bytes outstanding beyond `snd_una`,
    /// one ≤MSS segment at a time via `send`. The body is read on demand, never held.
    fn pump(&mut self, now_ms: u64, window: usize, send: &mut dyn FnMut(&[u8])) {
        let total = match self.conn.resp.as_ref() {
            Some(r) => r.total_len,
            None => return,
        };
        loop {
            let edge = self.acked_bytes().saturating_add(window).min(total);
            let next = self.sent_bytes();
            if next >= edge {
                break;
            }
            let want = (edge - next).min(MSS);
            let mut buf = [0u8; MSS];
            let n = self.read_response(next, &mut buf[..want]);
            if n == 0 {
                break;
            }
            let is_last = next + n >= total;
            let f = if is_last { PSH | ACK | FIN } else { PSH | ACK };
            send(&self.segment(f, &buf[..n]));
            self.conn.snd_nxt = self.conn.snd_nxt.wrapping_add(n as u32);
            self.conn.last_send_ms = now_ms;
            if is_last {
                self.conn.snd_nxt = self.conn.snd_nxt.wrapping_add(1); // FIN consumes one
                if let Some(r) = self.conn.resp.as_mut() {
                    r.fin_sent = true;
                }
                break;
            }
        }
    }

    /// Route the request, parse any `Range:`, render headers, and stage `RespState`.
    fn build_response(&mut self, req: &[u8]) {
        let reply = self.route_request(req);
        let total_body = reply.source.total_len();
        let (status, body_base, content_len) = match parse_range(req, total_body) {
            RangeResult::None => (reply.status, 0, total_body),
            RangeResult::Sat(a, b) => (206, a, b - a + 1),
            RangeResult::Unsat => (416, 0, 0),
        };
        let headers = render_headers(status, reply.content_type, body_base, content_len, total_body);
        let hdr_len = headers.len();
        let total_len = hdr_len + content_len;
        self.conn.resp = Some(RespState {
            headers,
            hdr_len,
            source: reply.source,
            body_base,
            total_len,
            fin_sent: false,
        });
    }

    /// Send a RST for the current connection and tear it down.
    fn reset_with_rst(&mut self, send: &mut dyn FnMut(&[u8])) {
        send(&self.segment(RST, &[]));
        self.conn = Conn::default();
    }

    /// Route one HTTP request: try the installed application handler first, then
    /// fall back to the built-in control panel (text/html).
    fn route_request(&mut self, req: &[u8]) -> HttpReply {
        let line = first_line(req);
        let mut parts = line.split(' ');
        let method = parts.next().unwrap_or("");
        let target = parts.next().unwrap_or("/");
        let (path, query) = match target.split_once('?') {
            Some((p, q)) => (p, q),
            None => (target, ""),
        };
        if let Some(h) = self.handler {
            if let Some(r) = h(method, path, query, http_body(req)) {
                return r;
            }
        }
        let (page, action) = builtin_route(path, query, &self.conn.our_ip);
        self.action = action;
        HttpReply::ok_owned("text/html; charset=utf-8", page)
    }

    /// Build an inner IPv4 + TCP segment from the dongle to the client.
    fn segment(&self, flags: u8, payload: &[u8]) -> Vec<u8> {
        let c = &self.conn;
        let tcp_len = 20 + payload.len();
        let total = 20 + tcp_len;
        let mut pkt = vec![0u8; total];

        // IPv4 header
        pkt[0] = 0x45;
        pkt[2..4].copy_from_slice(&(total as u16).to_be_bytes());
        pkt[6] = 0x40; // Don't Fragment
        pkt[8] = 64; // TTL
        pkt[9] = PROTO_TCP;
        pkt[12..16].copy_from_slice(&c.our_ip);
        pkt[16..20].copy_from_slice(&c.client_ip);
        let ipsum = checksum(&pkt[..20]);
        pkt[10..12].copy_from_slice(&ipsum.to_be_bytes());

        // TCP header
        let t = &mut pkt[20..];
        t[0..2].copy_from_slice(&HTTP_PORT.to_be_bytes());
        t[2..4].copy_from_slice(&c.client_port.to_be_bytes());
        t[4..8].copy_from_slice(&c.snd_nxt.to_be_bytes());
        t[8..12].copy_from_slice(&c.rcv_nxt.to_be_bytes());
        t[12] = (5 << 4) | 0; // data offset = 5 words (20 bytes), no options
        t[13] = flags;
        t[14..16].copy_from_slice(&64240u16.to_be_bytes()); // window
        t[20..].copy_from_slice(payload);

        let tsum = tcp_checksum(&c.our_ip, &c.client_ip, &pkt[20..]);
        pkt[36..38].copy_from_slice(&tsum.to_be_bytes());
        pkt
    }
}

/// Render the HTTP status line + headers for a (possibly partial) response.
fn render_headers(
    status: u16,
    content_type: &str,
    body_base: usize,
    content_len: usize,
    total: usize,
) -> Vec<u8> {
    let reason = match status {
        200 => "OK",
        206 => "Partial Content",
        416 => "Range Not Satisfiable",
        _ => "OK",
    };
    let mut h = format!(
        "HTTP/1.1 {status} {reason}\r\nContent-Type: {content_type}\r\nContent-Length: {content_len}\r\nConnection: close\r\nAccess-Control-Allow-Origin: *\r\nAccept-Ranges: bytes\r\n"
    );
    if status == 206 {
        h.push_str(&format!(
            "Content-Range: bytes {}-{}/{}\r\n",
            body_base,
            body_base + content_len - 1,
            total
        ));
    } else if status == 416 {
        h.push_str(&format!("Content-Range: bytes */{}\r\n", total));
    }
    h.push_str("\r\n");
    h.into_bytes()
}

/// Result of parsing a request's `Range:` header against a body of `total` bytes.
enum RangeResult {
    None,         // no Range header → full 200
    Sat(usize, usize), // satisfiable [a, b] inclusive
    Unsat,        // present but unsatisfiable → 416
}

/// Parse a single `Range: bytes=A-B` / `A-` / `-N` header (no multipart). Clamps to
/// the body; an out-of-range start is `Unsat`.
fn parse_range(req: &[u8], total: usize) -> RangeResult {
    let text = match core::str::from_utf8(req) {
        Ok(t) => t,
        Err(_) => return RangeResult::None,
    };
    // Find the header line, case-insensitively, value after "bytes=".
    let mut spec: Option<&str> = None;
    for line in text.split("\r\n") {
        if let Some((name, val)) = line.split_once(':') {
            if name.trim().eq_ignore_ascii_case("range") {
                let v = val.trim();
                if let Some(rest) = v.strip_prefix("bytes=") {
                    spec = Some(rest.trim());
                }
                break;
            }
        }
    }
    let spec = match spec {
        Some(s) => s,
        None => return RangeResult::None,
    };
    if total == 0 {
        return RangeResult::Unsat;
    }
    // Only the first range of a (possibly comma-separated) set is honoured.
    let spec = spec.split(',').next().unwrap_or("").trim();
    let (a, b) = match spec.split_once('-') {
        Some(("", suffix)) => {
            // "-N": last N bytes.
            let n: usize = match suffix.trim().parse() {
                Ok(n) if n > 0 => n,
                _ => return RangeResult::Unsat,
            };
            let n = n.min(total);
            (total - n, total - 1)
        }
        Some((start, "")) => {
            // "A-": from A to end.
            let a: usize = match start.trim().parse() {
                Ok(a) => a,
                _ => return RangeResult::Unsat,
            };
            if a >= total {
                return RangeResult::Unsat;
            }
            (a, total - 1)
        }
        Some((start, end)) => {
            let a: usize = match start.trim().parse() {
                Ok(a) => a,
                _ => return RangeResult::Unsat,
            };
            let b: usize = match end.trim().parse() {
                Ok(b) => b,
                _ => return RangeResult::Unsat,
            };
            if a >= total || a > b {
                return RangeResult::Unsat;
            }
            (a, b.min(total - 1))
        }
        None => return RangeResult::Unsat,
    };
    RangeResult::Sat(a, b)
}

/// Sequence-number "less than", wraparound-safe (RFC 1982 serial comparison).
fn seq_lt(a: u32, b: u32) -> bool {
    (a.wrapping_sub(b) as i32) < 0
}

/// Built-in control panel routes (GET-only). The application handler runs first;
/// this is the fallback for paths it doesn't claim.
fn builtin_route(path: &str, query: &str, our_ip: &[u8; 4]) -> (Vec<u8>, Option<TcpAction>) {
    match path {
        "/led/on" => (ok_page(), Some(TcpAction::LedOn)),
        "/led/off" => (ok_page(), Some(TcpAction::LedOff)),
        "/screen/on" => (ok_page(), Some(TcpAction::ScreenOn)),
        "/screen/off" => (ok_page(), Some(TcpAction::ScreenOff)),
        "/flash" => (ok_page(), Some(TcpAction::Flash)),
        "/default" => (ok_page(), Some(TcpAction::Default)),
        "/text" => {
            let msg = url_decode(query_get(query, "msg"));
            (ok_page(), Some(TcpAction::Text(msg)))
        }
        _ => (control_page(our_ip), None),
    }
}

/// The control panel: buttons (GET links) + a text form. Kept small enough to
/// fit in a single TCP segment (our server sends one data+FIN segment).
fn control_page(our_ip: &[u8; 4]) -> Vec<u8> {
    format!(
        "<!doctype html><html><head><meta charset=utf-8>\
<meta name=viewport content=\"width=device-width,initial-scale=1\">\
<title>T-Dongle S3</title><style>\
body{{font-family:sans-serif;background:#111;color:#eee;text-align:center;margin:1em}}\
a,button{{display:inline-block;margin:5px;padding:11px 16px;background:#1e88e5;\
color:#fff;text-decoration:none;border:0;border-radius:7px;font-size:1em}}\
input{{padding:10px;border-radius:7px;border:0;font-size:1em;width:60%}}\
</style></head><body><h2>T-Dongle S3</h2><p>{}.{}.{}.{}</p>\
<a href=/screen/on>Skjerm på</a><a href=/screen/off>Skjerm av</a><br>\
<a href=/led/on>LED på</a><a href=/led/off>LED av</a><br>\
<a href=/flash>Blink s/h ×3</a><a href=/default>Standard info</a>\
<form action=/text><br><input name=msg placeholder=\"Tekst til skjerm\"><br>\
<button>Vis tekst</button></form></body></html>",
        our_ip[0], our_ip[1], our_ip[2], our_ip[3]
    )
    .into_bytes()
}

/// Tiny response for an action: confirm + auto-redirect back to the panel.
fn ok_page() -> Vec<u8> {
    b"<!doctype html><html><head><meta charset=utf-8>\
<meta http-equiv=refresh content=\"1;url=/\"></head>\
<body style=\"background:#111;color:#eee;font-family:sans-serif;text-align:center\">\
<p>OK</p><a href=/ style=color:#9cf>&larr; tilbake</a></body></html>"
        .to_vec()
}

/// The request body: everything after the `\r\n\r\n` header terminator. Empty
/// if there is no body (e.g. a GET) or the terminator isn't in this segment.
fn http_body(req: &[u8]) -> &[u8] {
    let n = req.len();
    let mut i = 0;
    while i + 4 <= n {
        if &req[i..i + 4] == b"\r\n\r\n" {
            return &req[i + 4..];
        }
        i += 1;
    }
    &[]
}

/// First request line (up to CR/LF) as a str.
fn first_line(req: &[u8]) -> &str {
    let end = req
        .iter()
        .position(|&b| b == b'\r' || b == b'\n')
        .unwrap_or(req.len());
    core::str::from_utf8(&req[..end]).unwrap_or("")
}

/// Value of `key` in an `a=b&c=d` query string, or "".
fn query_get<'a>(query: &'a str, key: &str) -> &'a str {
    for kv in query.split('&') {
        if let Some((k, v)) = kv.split_once('=') {
            if k == key {
                return v;
            }
        }
    }
    ""
}

/// Percent-decode a query value (`+` -> space, `%XX` -> byte), UTF-8 lossy.
fn url_decode(s: &str) -> String {
    let b = s.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        match b[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < b.len() => match (hexval(b[i + 1]), hexval(b[i + 2])) {
                (Some(h), Some(l)) => {
                    out.push(h * 16 + l);
                    i += 3;
                }
                _ => {
                    out.push(b'%');
                    i += 1;
                }
            },
            c => {
                out.push(c);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn hexval(c: u8) -> Option<u8> {
    match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    }
}

/// IPv4 / generic 16-bit one's-complement checksum.
fn checksum(data: &[u8]) -> u16 {
    finish(sum16(data, 0))
}

/// TCP checksum over the pseudo-header + TCP segment.
fn tcp_checksum(src: &[u8; 4], dst: &[u8; 4], tcp: &[u8]) -> u16 {
    let mut s: u32 = 0;
    let mut ph = [0u8; 12];
    ph[0..4].copy_from_slice(src);
    ph[4..8].copy_from_slice(dst);
    ph[9] = PROTO_TCP;
    ph[10..12].copy_from_slice(&(tcp.len() as u16).to_be_bytes());
    s = sum16(&ph, s);
    s = sum16(tcp, s);
    finish(s)
}

fn sum16(data: &[u8], mut sum: u32) -> u32 {
    let mut i = 0;
    while i + 1 < data.len() {
        sum += u16::from_be_bytes([data[i], data[i + 1]]) as u32;
        i += 2;
    }
    if i < data.len() {
        sum += (data[i] as u32) << 8;
    }
    sum
}

fn finish(mut sum: u32) -> u16 {
    while sum >> 16 != 0 {
        sum = (sum & 0xffff) + (sum >> 16);
    }
    !(sum as u16)
}

fn rand_u32() -> u32 {
    let mut b = [0u8; 4];
    getrandom::getrandom(&mut b).expect("getrandom");
    u32::from_le_bytes(b)
}
